import { useLocation, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Download, Share } from "lucide-react";
import NarrativeReportSection from "@/components/report/NarrativeReportSection";
import VisualizationsSection from "@/components/report/VisualizationsSection";

interface ReportData {
  report_id: string;
  storyteller_output: {
    executive_summary: string;
    key_findings: string[];
    data_overview: string;
    analysis_narrative: string;
    visualizations_summary: string;
    qa_considerations?: string;
    conclusion: string;
  };
  chart_data: Array<{
    data?: any;
    layout?: any;
    config?: any;
    error?: string;
  }>;
}

const Report = () => {
  const navigate = useNavigate();
  const location = useLocation();
  
  // Get report data from navigation state or use mock data
  const reportData: ReportData = location.state?.reportData || {
    report_id: "sample-report",
    storyteller_output: {
      executive_summary: "Sample analysis report showing data insights and trends.",
      key_findings: ["Sample finding 1", "Sample finding 2"],
      data_overview: "Sample data overview",
      analysis_narrative: "Sample analysis narrative",
      visualizations_summary: "Sample visualization summary",
      conclusion: "Sample conclusion"
    },
    chart_data: []
  };

  const handleNewAnalysis = () => {
    navigate("/upload");
  };

  const handleDownloadReport = () => {
    // Placeholder for report download functionality
    console.log("Download report:", reportData.report_id);
  };

  const handleShareReport = () => {
    // Placeholder for report sharing functionality  
    console.log("Share report:", reportData.report_id);
  };

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border/60 bg-background/80 backdrop-blur-xl">
        <div className="container flex h-20 items-center justify-between px-4 md:px-6">
          <div className="flex items-center gap-4">
            <Button 
              variant="ghost" 
              onClick={() => navigate("/")}
              className="gap-2 text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Button>
            <div className="hidden items-center gap-3 lg:flex">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-primary text-sm font-semibold text-primary-foreground shadow-glow">
                A
              </div>
              <div>
                <p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Mission Console</p>
                <p className="text-lg font-semibold tracking-tight">AnalytIQ</p>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <Badge variant="outline" className="hidden border-border/70 bg-card/70 md:inline-flex">
              Report ID: {reportData.report_id.slice(0, 8)}...
            </Badge>
            <Button variant="outline" size="sm" onClick={handleDownloadReport} className="border-border/70 bg-card/70 hover:bg-card">
              <Download className="h-4 w-4 mr-1" />
              Download
            </Button>
            <Button variant="outline" size="sm" onClick={handleShareReport} className="border-border/70 bg-card/70 hover:bg-card">
              <Share className="h-4 w-4 mr-1" />
              Share
            </Button>
            <Button onClick={handleNewAnalysis} className="bg-gradient-primary text-primary-foreground shadow-glow">
              New Analysis
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container px-4 md:px-6 py-8">
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Page Title */}
          <div className="text-center space-y-4">
            <h1 className="text-balance text-4xl font-semibold tracking-tight md:text-6xl">
              Analysis{" "}
              <span className="bg-gradient-primary bg-clip-text text-transparent">
                Report
              </span>
            </h1>
            <p className="mx-auto max-w-3xl text-lg text-muted-foreground md:text-xl">
              Mission-ready intelligence generated by your autonomous analyst fleet.
            </p>
          </div>

          {/* Narrative Report Section */}
          <NarrativeReportSection storytellerOutput={reportData.storyteller_output} />

          {/* Visualizations Section */}
          <VisualizationsSection chartData={reportData.chart_data} />

          {/* Action Buttons */}
          <div className="text-center pt-8">
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                onClick={handleNewAnalysis}
                className="bg-gradient-primary text-primary-foreground shadow-glow transition-transform duration-300 hover:scale-[1.02]"
              >
                Analyze Another Dataset
              </Button>
              <Button 
                variant="outline" 
                size="lg"
                onClick={handleDownloadReport}
              >
                Download Full Report
              </Button>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/40 py-8 mt-16">
        <div className="container px-4 md:px-6 text-center">
          <p className="text-sm text-muted-foreground">
            © 2024 AnalytIQ. Analysis completed by AI-powered data agents.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Report;
