import { useLocation, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Download, Share } from "lucide-react";
import NarrativeReportSection from "@/components/report/NarrativeReportSection";
import VisualizationsSection from "@/components/report/VisualizationsSection";

interface ReportData {
  report_id: string;
  storyteller_output: {
    executive_summary: string;
    key_findings: string[];
    data_overview: string;
    analysis_narrative: string;
    visualizations_summary: string;
    qa_considerations?: string;
    conclusion: string;
  };
  chart_data: Array<{
    data?: any;
    layout?: any;
    config?: any;
    error?: string;
  }>;
}

const Report = () => {
  const navigate = useNavigate();
  const location = useLocation();
  
  // Get report data from navigation state or use mock data
  const reportData: ReportData = location.state?.reportData || {
    report_id: "sample-report",
    storyteller_output: {
      executive_summary: "Sample analysis report showing data insights and trends.",
      key_findings: ["Sample finding 1", "Sample finding 2"],
      data_overview: "Sample data overview",
      analysis_narrative: "Sample analysis narrative",
      visualizations_summary: "Sample visualization summary",
      conclusion: "Sample conclusion"
    },
    chart_data: []
  };

  const handleNewAnalysis = () => {
    navigate("/upload");
  };

  const handleDownloadReport = () => {
    // Placeholder for report download functionality
    console.log("Download report:", reportData.report_id);
  };

  const handleShareReport = () => {
    // Placeholder for report sharing functionality  
    console.log("Share report:", reportData.report_id);
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border/40 bg-background/95 backdrop-blur">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <div className="flex items-center gap-4">
            <Button 
              variant="ghost" 
              onClick={() => navigate("/")}
              className="gap-2"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Button>
            <div className="hidden md:flex items-center space-x-2">
              <div className="h-8 w-8 rounded-lg bg-gradient-primary flex items-center justify-center">
                <span className="text-white font-bold text-sm">A</span>
              </div>
              <span className="text-xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                AnalytIQ
              </span>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <Badge variant="outline" className="hidden md:inline-flex">
              Report ID: {reportData.report_id.slice(0, 8)}...
            </Badge>
            <Button variant="outline" size="sm" onClick={handleDownloadReport}>
              <Download className="h-4 w-4 mr-1" />
              Download
            </Button>
            <Button variant="outline" size="sm" onClick={handleShareReport}>
              <Share className="h-4 w-4 mr-1" />
              Share
            </Button>
            <Button onClick={handleNewAnalysis} className="bg-gradient-primary">
              New Analysis
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container px-4 md:px-6 py-8">
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Page Title */}
          <div className="text-center space-y-4">
            <h1 className="text-4xl md:text-5xl font-bold">
              Analysis{" "}
              <span className="bg-gradient-primary bg-clip-text text-transparent">
                Report
              </span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Comprehensive insights generated by our AI analyst team
            </p>
          </div>

          {/* Narrative Report Section */}
          <NarrativeReportSection storytellerOutput={reportData.storyteller_output} />

          {/* Visualizations Section */}
          <VisualizationsSection chartData={reportData.chart_data} />

          {/* Action Buttons */}
          <div className="text-center pt-8">
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                onClick={handleNewAnalysis}
                className="bg-gradient-primary hover:shadow-glow transition-all duration-300"
              >
                Analyze Another Dataset
              </Button>
              <Button 
                variant="outline" 
                size="lg"
                onClick={handleDownloadReport}
              >
                Download Full Report
              </Button>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/40 py-8 mt-16">
        <div className="container px-4 md:px-6 text-center">
          <p className="text-sm text-muted-foreground">
            © 2024 AnalytIQ. Analysis completed by AI-powered data agents.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Report;